apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.giropops.name }}
  namespace: {{ .Values.giropops.namespace }}
  annotations:
    ingress.kubernetes.io/ssl-redirect: "{{ .Values.giropops.ingress.annotations.sslRedirect }}"
    traefik.ingress.kubernetes.io/router.entrypoints: {{ .Values.giropops.ingress.annotations.entrypoints }}
spec:
  rules:
    - host: {{ .Values.giropops.ingress.host }}
      http:
        paths:
          - path: {{ .Values.giropops.ingress.path }}
            pathType: {{ .Values.giropops.ingress.pathType }}
            backend:
              service:
                name: {{ .Values.giropops.service.name }}
                port:
                  number: {{ .Values.giropops.service.port }}
