apiVersion: v1
kind: Service
metadata:
  name: giropops-senhas
spec:
  selector:
    app: giropops-senhas
  ports:
    - protocol: TCP
      port: {{ .Values.giropops.service.port }}
      targetPort: {{ .Values.giropops.service.port }}
  type: {{ .Values.giropops.service.type }}
