{
 "title": "Giropops-Senhas",
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Memory Usage - Node",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(instance) (instance:node_memory_utilisation:ratio)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods per Namespace",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(namespace) (node_namespace_pod:kube_pod_info:)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Passwords Generated - Total",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(container) (senha_gerada_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage - POD",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(container) (container_memory_usage_bytes)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}