apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.giropops.service.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.giropops.labels.app }}
  ports:
    - protocol: {{ .Values.giropops.service.protocol }}
      port: {{ .Values.giropops.service.port }}
      targetPort: {{ .Values.giropops.service.port }}
  type: {{ .Values.giropops.service.type }}
