apiVersion: apps/v1
kind: Deployment
metadata:
  name: redisdb
  namespace: giropops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redisdb
  template:
    metadata:
      labels:
        app: redisdb
    spec:
      containers:
      - name: redisdb
        image: cgr.dev/chainguard/redis:latest
